### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by gnunn1** [d-language-server/dls#14]
I'm trying this out but it doesn't appear to be working, I see the following errors in the Developer Tools console:

```
notificationsAlerts.ts:42 Internal error
t.onDidNotificationChange @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
t.notify @ notifications.ts:115
t.notify @ notificationService.ts:54
e._showMessage @ mainThreadMessageService.ts:84
e._showMessage @ mainThreadMessageService.ts:45
e.$showMessage @ mainThreadMessageService.ts:39
t._doInvokeHandler @ rpcProtocol.ts:442
t._invokeHandler @ rpcProtocol.ts:427
t._receiveRequest @ rpcProtocol.ts:344
t._receiveOneMessage @ rpcProtocol.ts:274
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
mainThreadExtensionService.ts:43 [LaurentTreguier.vscode-dls]Internal error
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
t._doInvokeHandler @ rpcProtocol.ts:442
t._invokeHandler @ rpcProtocol.ts:427
t._receiveRequest @ rpcProtocol.ts:344
t._receiveOneMessage @ rpcProtocol.ts:274
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:44 Error: Internal error
	at handleResponse (/home/gnunn/.vscode/extensions/laurenttreguier.vscode-dls-1.11.6/node_modules/vscode-jsonrpc/lib/main.js:436:48)
	at processMessageQueue (/home/gnunn/.vscode/extensions/laurenttreguier.vscode-dls-1.11.6/node_modules/vscode-jsonrpc/lib/main.js:263:17)
	at Immediate.setImmediate [as _onImmediate] (/home/gnunn/.vscode/extensions/laurenttreguier.vscode-dls-1.11.6/node_modules/vscode-jsonrpc/lib/main.js:247:13)
	at runCallback (timers.js:789:20)
	at tryOnImmediate (timers.js:751:5)
	at processImmediate [as _immediateCallback] (timers.js:722:5)
```

I've done at ```dub fetch dls``` and ```dub run --arch=x86_64 dls:bootstrap```. If I manually run the dls executable it runs fine.

Any suggestions?

**Comment by gnunn1** [comment]
This is on Arch Linux (64 bit) with VS Code 1.28.2

**Comment by LaurentTreguier** [comment]
What project have you tried opening ? I always test it against dub projects, and not so much with non-dub ones, it has a higher chance of failure with these.
I tried opening tilix, and didn't run into any problem so far.
Maybe I'm going to add an option to log stuff in a temporary file, that would make debugging easier.

**Comment by LaurentTreguier** [comment]
With the latest versions dls and vscode-dls, you should be able to set `d.init.logFile` to log things in a file, and see where it all comes crashing down.

**Comment by LaurentTreguier** [comment]
No problem, just go back to this issue whenever you get back to this :+1:
